#!/bin/bash

if [ -z "${OBSIDIAN_VAULT}" ]; then
  echo "No vault was found (OBSIDIAN_VAULT variable is unset)"
  exit 1
else

  VAULT_DIR="${OBSIDIAN_VAULT}";
fi


HOSTNAME=$( hostname | sed 's/[^a-zA-Z0-9 ]//g' | sed 's/[ _]/-/g')
LOG_DIR="$NOTE_STORE" || "$OBSIDIAN_VAULT/Heap/Logs"
mkdir -p "$LOG_DIR"


eval "$EDITOR $LOG_DIR/$(date +%s)__${HOSTNAME}__log.md"



