#!/bin/bash

git log  --pretty=tformat: --numstat -bw --after="$(date -I) 00:00" --before="$(date -I) 23:59"\
| gawk '{ add += $1 ; subs += $2 ; loc += $1 - $2 } END { printf "Added lines:%s \nRemoved lines :%s \nNet lines: %s\n",add,subs,loc }' -

