#!/bin/bash


incl=("iostream" "string" "vector")

mainargs="void"




target="$1.cpp"
if [[ -f "$target" ]]; then
  echo "$target already exists!";
  exit 1
fi

touch $target

fileadd(){
  echo "$@" >> "$target"
}

blankline(){

  for (( i=0; i<$1; i++ )); do
    echo "" >> "$target";
  done

}

fileadd "/* $(date -I) */ "
blankline 2

for line in "${incl[@]}"; do
  fileadd "#include <$line>" 
done

blankline 2

fileadd "using std::string;"
fileadd "using std::vector;"
fileadd "using std::cout;"
fileadd "using std::cin;"

blankline 2

fileadd "int main($mainargs){ return 0; }"
clang-format "$target" -i -style=llvm

if [[ "g" == "$2" ]]; then
  neovide --maximized "$target" &
else

$EDITOR "$target" 

fi

