#!/bin/bash


 if ruff . --per-file-ignores __init__.py:F401 --fix --show-fixes  --show-source  ; then

  echo "Ruff ran successfully! 😌"
 else
  echo "Ruff found problems, fix them! 😭"
   exit 2
fi

black . --quiet &> /dev/null
